version: "3.9"

services:
  app1:
    build: ./app
  app2:
    build: ./app
  app3:
    build: ./app        
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
  redis:
    image: redis:latest    